### ISSUE TITLE
How to produce the masked dataset?

### ISSUE THREAD

**Issue by v587su** [RoBERTaCode/roberta#1]
Could you please share the code for processing the raw dataset, or just tell me the way to process it? 
Thank you!

**Comment by RoBERTaCode** [comment]
Hi, thank you for your question!
For the **construct level masking** dataset, we look for "if", "for", "while", "catch" and we masked the code in the following round brackets. We also masked the parameters in each method invocation, excluding the signature, identified using the abstract code (you can find the abstraction tool here: https://github.com/micheletufano/src2abs)
For the **token level masking** dataset, we simply masked a random number of tokens at the end of each line (from 1 to 10 tokens)
Finally, for the **block level masking** dataset, we used SrcML (https://www.srcml.org/) to identify the blocks to be masked.
The resulting files can be found in `DATASET` folder.

**Comment by v587su** [comment]
Thanks for your timely response.
